project_id = "zhvfoyglmdhsmavzbevc"

[functions.create-user-admin]
verify_jwt = false

[functions.notificar-error-canje]
verify_jwt = false

[functions.send-campaign-emails]
verify_jwt = false

[functions.generate-email-template]
verify_jwt = false
