// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhvfoyglmdhsmavzbevc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodmZveWdsbWRoc21hdnpiZXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMjIyMzEsImV4cCI6MjA3NTU5ODIzMX0.PILpWxY4AlV1cRgYwkZhxiEAP2u55LhQik6epTIzGjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});